site_name: Lucas Dias Ramos - My Docs
site_url: https://lucasdias-infosec.github.io/infosec-portfolio/
repo_url: https://github.com/lucasdias-infosec/infosec-portfolio/
repo_name: lucasdias-infosec/infosec-portfolio/
edit_uri: edit/main/docs/
theme:
  name: material
  language: en
  logo: assets/Logo.png  
  favicon: assets/Logo.png 
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
nav:
  - Home: index.md
  - Project Blue-Team-Lab:
    - PT-BR:
      - Introdução: Blue-Team-Lab/PT-BR/Blue-Team-Lab-PT-BR.md
      - Base da Infraestutura e Intalação de Ferramentas:
      - Base da Infraestrutura: Blue-Team-Lab/PT-BR/00-base-infra.md
    - Guia-de-Contribuições: Blue-Team-Lab/PT-BR/Guia-de-Contribuições.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lucasdias-infosec
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/lucas-dias-ramos-a435a0369
    - icon: fontawesome/solid/envelope
      link: mailto:lucas.dias.ramos.pro@gmail.com
      name: E-mail
    - icon: fontawesome/solid/scale-balanced
      link: Blue-Team-Lab/PT-BR/ETICA/
      name: Professional Code of Ethics
      
